# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-01 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinal',
            name='configuracao_da_mao',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='expressao_facil_corporal',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='movimento',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='orientacao_das_maos',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='ponto_de_articulacao',
            field=models.CharField(max_length=4),
        ),
    ]
